# Numpy 
<hr
style="borders:2.5px solid 
#000000ff">
</hr>

<b>Krizzia Jenna H. Peregrina</b>
<br>Computer Engineer

In [ ]:
#imports and packages
import numpy as np

#  1D Array

In [ ]:
my_array = [1, 2, 3]

In [ ]:
type(my_array)

list

In [ ]:
my_array = np.array([my_array])

In [ ]:
np.shape(my_array)

(3,)

# 2D Array

In [ ]:
my_array = np.array([
    [1,2,3],
    [4,5,6],
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.shape(my_array)

(2, 3)

In [45]:
trans_array = my_array.T

In [46]:
trans_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [47]:
np.shape(trans_array)

(3, 2)

In [ ]:
np.sum(trans_array, axis=0) 

array([ 6, 15])

In [ ]:
np.sum(trans_array, axis=1) 

array([5, 7, 9])

# Measure of Central Tendency

In [ ]:
resistance = np.array([
    [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 10.4, 3, 9.8], #jaguar
    [10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2, 9.1, 9.1, np.nan] #panther
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [ ]:
#Mean
np.nanmean(resistance, axis=1)

array([ 9.4 , 10.75])