# Numpy Basics
<hr
style="borders:2.5px solid 
#000000ff">
</hr>

<b>Krizzia Jenna H. Peregrina</b>
<br>Computer Engineer

In [11]:
import numpy as np
from scipy import stats
from statistics import multimode

# 1D Array

In [12]:
array_a = np.array([1, 2, 3])
array_a

array([1, 2, 3])

In [13]:
np.shape(array_a)

(3,)

In [14]:
array_b = np.array([4, 5, 6])
array_b

array([4, 5, 6])

# 2D Array

In [15]:
my_array = np.array([[1, 2, 3], 
                     [4, 5, 6]])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.shape(my_array)

(2, 3)

In [17]:
t_array = my_array.T
t_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [18]:
np.shape(t_array)

(3, 2)

# Measures of Central Tendency

In [19]:
resistance = np.array([
    [10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8],
    [10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1,np.nan]
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [20]:
np.shape(resistance)

(2, 11)

In [21]:
resistance.T

array([[10.6, 10.1],
       [ 9.1, 11. ],
       [ 9.3,  9.1],
       [ 9.8, 20. ],
       [10.5,  9.2],
       [10.4, 10.8],
       [ 9.5,  9.9],
       [11. ,  9.2],
       [10.4,  9.1],
       [ 3. ,  9.1],
       [ 9.8,  nan]])

In [22]:
np.mean(resistance, axis=0)

array([10.35, 10.05,  9.2 , 14.9 ,  9.85, 10.6 ,  9.7 , 10.1 ,  9.75,
        6.05,   nan])

In [23]:
np.mean(resistance, axis=1)

array([9.4, nan])

In [24]:
np.nanmean(resistance, axis=1)

array([ 9.4 , 10.75])